---
- name: Create file 
  hosts: all
  tasks:
    - name: Create file
      file:
        path: /tmp/file1
        state: touch
        access_time: 20180502
      when: ansible_distribution == "Ubuntu" "Centos" "Dedian"
